config/routes.rb
MyCar::Application.routes.draw do
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :car_items

  resources :leases

  devise_for :users

  get "main/index"
  root 'main#index', as: 'main'
  resources :cars do
    resources :reviews
    resources :build, controller: 'cars/build'
    member do
      get 'edit_location'
      get 'edit_pictures'
      get 'edit_calendar'
    end
  end

  post 'cars/search' => 'cars#search'

end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lease, only: [:show, :edit, :update, :destroy]

  # GET /leases
  # GET /leases.json
  def index
    @leases = Lease.all
  end

  # GET /leases/1
  # GET /leases/1.json
  def show
  end

  # GET /leases/new
  def new
    @lease = Lease.new
  end

  # GET /leases/1/edit
  def edit
  end

  # POST /leases
  # POST /leases.json
  def create
    @lease = Lease.new(lease_params)

    respond_to do |format|
      if @lease.save
        format.html { redirect_to @lease, notice: 'Lease was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lease }
      else
        format.html { render action: 'new' }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leases/1
  # PATCH/PUT /leases/1.json
  def update
    respond_to do |format|
      if @lease.update(lease_params)
        format.html { redirect_to @lease, notice: 'Lease was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leases/1
  # DELETE /leases/1.json
  def destroy
    @lease.destroy
    respond_to do |format|
      format.html { redirect_to leases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lease
      @lease = Lease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lease_params
      params[:lease]
    end
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/views/leases/_form.html.erb
<%= form_for(@lease) do |f| %>
  <% if @lease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lease.errors.count, "error") %> prohibited this lease from being saved:</h2>

      <ul>
      <% @lease.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leases/edit.html.erb
<h1>Editing lease</h1>

<%= render 'form' %>

<%= link_to 'Show', @lease %> |
<%= link_to 'Back', leases_path %>

app/views/leases/index.html.erb
<h1>Listing leases</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @leases.each do |lease| %>
      <tr>
        <td><%= link_to 'Show', lease %></td>
        <td><%= link_to 'Edit', edit_lease_path(lease) %></td>
        <td><%= link_to 'Destroy', lease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lease', new_lease_path %>

app/views/leases/new.html.erb
<h1>New lease</h1>

<%= render 'form' %>

<%= link_to 'Back', leases_path %>

app/views/leases/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Your Lease</h2>


<ul>
	<% @lease.car_items.each do |item| %>
		<li><%= item.car.brand %></li>
	<% end %>
</ul>