config/routes.rb
MyCar::Application.routes.draw do
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :car_items

  resources :leases

  devise_for :users

  get "main/index"
  root 'main#index', as: 'main'
  resources :cars do
    resources :reviews
    resources :build, controller: 'cars/build'
    member do
      get 'edit_location'
      get 'edit_pictures'
      get 'edit_calendar'
    end
  end

  post 'cars/search' => 'cars#search'

end

app/models/car.rb
class Car < ActiveRecord::Base
	has_many :car_items
	has_many :reviews, dependent: :destroy
	has_many :pictures, :dependent => :destroy
	belongs_to :user
	belongs_to :brand
#Validation
	validates_presence_of :brand_id
	validates_presence_of :model
	validates_presence_of :price
	validates_presence_of :mileage
	validates :price, numericality: {greater_than_or_equal_to: 100}
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/  
  	before_destroy :ensure_not_referenced_by_any_car_item
  	geocoded_by :location
  	after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }
	accepts_nested_attributes_for :pictures, allow_destroy: true

	def self.search(search)				
		search_condition = "%" + search + "%"
		find(:all, :conditions => ['location LIKE ? OR remarks LIKE ?', search_condition, search_condition])
		#  search_condition = "%" + search + "%"
		 # find(:all, :conditions => ['location LIKE ? OR remarks LIKE ?', search_condition, search_condition])
	end

	private

		def ensure_not_referenced_by_any_car_item
			if car_items.empty?
				return true
			else
				errors.add(:base, 'car_items present')
				return false
			end
		end

end

app/controllers/cars/build_controller.rb
class Cars::BuildController < ApplicationController
  include Wicked::Wizard

  steps :location, :picture

  def show
    @car = Car.find(params[:car_id])
      case step
      when :picture
        10.times {@car.pictures.build}
      end
    render_wizard
  end

  def update
    @car = Car.find(params[:car_id])
    @car.update(car_params)
    render_wizard @car
  end

  def create
    @car = Car.create
    redirect_to wizard_path(steps.first, :car_id => @car.id)
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def car_params
    params.require(:car).permit(:brand, :model, :year, :rentaldates, :price, :location, :auto_transmission, :mileage, :color, :image_url, :remarks, :avatar, :brand_id, pictures_attributes: [:title, :image, :_destroy])
  end

  def finish_wizard_path
    cars_path
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_car, only: [:edit, :update, :destroy,
    :edit_location, :edit_pictures, :edit_calendar]
  
  # GET /cars
  # GET /cars.json
  def index
    if current_user.blank?
      #redirect_to user_session_path
      @cars = {}
    else
      @cars = current_user.cars
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id]) #current_user.cars.find(params[:id])
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # GET /cars/1/edit_location
  def edit_location
  end

  # GET /cars/1/edit_pictures
  def edit_pictures

  end

  # GET /cars/1/edit_calendar
  def edit_calendar    
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = current_user.cars.new(car_params)
  
    respond_to do |format|
      if @car.save
        format.html { redirect_to car_build_index_path @car }

        #format.html { redirect_to @car, notice: 'Car was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update

    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  def search
    @cars = Car.search params[:search]
    @hash = Gmaps4rails.build_markers(@cars) do |car, marker|
      marker.lat car.latitude
      marker.lng car.longitude
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
    #  if (params[:id].is_a? Integer)
        @car = current_user.cars.find(params[:id])
    #  else
    #    @car = current_user.cars.find(21)
    #  end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model, :year, :rentaldates, :price, :location,
        :auto_transmission, :mileage, :color, :image_url, :remarks, :avatar, :brand_id, pictures_attributes: [:id, :title, :image, :_destroy])
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_edit_menu.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %><small><%= " #{@car.brand.name} #{@car.model}" %></small></h1>
</div>

<ul class="nav nav-pills">
  <% if active == 'Basic' %>
  	<%= render text: '<li class="active">'.html_safe %>
  <% else %>
  	<%= render text: '<li>'.html_safe %>
  <% end %>
  <%= link_to 'Basic', edit_car_path(@car) %></li>   

  <% if active == 'Location' %>
  	<%= render text: '<li class="active">'.html_safe %>
  <% else %>
  	<%= render text: '<li>'.html_safe %>
  <% end %>
  <%= link_to 'Location', edit_location_car_path(@car) %></li>

  <% if active == 'Pictures' %>
  	<%= render text: '<li class="active">'.html_safe %>
  <% else %>
  	<%= render text: '<li>'.html_safe %>
  <% end %>
  <%= link_to 'Pictures', edit_pictures_car_path(@car) %></li>

  <% if active == 'Calendar' %>
  	<%= render text: '<li class="active">'.html_safe %>
  <% else %>
  	<%= render text: '<li>'.html_safe %>
  <% end %>
  <%= link_to 'Calendar', edit_calendar_car_path(@car) %></li>
</ul>

app/views/cars/_form.html.erb
<script>
  $(function() {
  $( "#datepicker" ).datepicker();
  });
</script>

<%= form_for @car, :html => { :multipart => true } do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand, :class => 'control-label' %>
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, {}, {:class=>'form-control'}) %>    
  </div>
  <div class="form-group">
    <%= f.label :model, :class => 'control-label' %>
    <%= f.text_field :model, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label' %>
    <%= f.text_field :year, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :rentaldates, :class => 'control-label' %>
    <%= f.text_field :rentaldates, :class => 'form-control', id: 'datepicker' %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label' %>
    <%= f.text_field :price, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label' %>
    <%= f.text_field :location, :class => 'form-control' %>
  </div>
  <div class="checkbox">
    <%= f.label :auto_transmission, :class => 'control-label' %>
    <%= f.check_box :auto_transmission %>
  </div>
  <div class="form-group">
    <%= f.label :mileage, :class => 'control-label' %>
    <%= f.text_field :mileage, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :color, :class => 'control-label' %>
    <%= f.text_field :color, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :remarks, :class => 'control-label' %>
    <%= f.text_field :remarks, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </div>  

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cars_path, :class => 'btn btn-default' %>

<% end %>

app/views/cars/edit.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %><small><%= " #{@car.brand.name} #{@car.model}" %></small></h1>
</div>

<ul class="nav nav-pills">
  <li class="active"><%= link_to 'Basic', edit_car_path(@car) %></li>   
  <li><%= link_to 'Location', edit_location_car_path(@car) %></li>
  <li><%= link_to 'Pictures', edit_pictures_car_path(@car) %></li>
  <li><%= link_to 'Calendar', edit_calendar_car_path(@car) %></li>
</ul>

<%= form_for @car do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :year, :class => 'control-label' %>
    <%= f.text_field :year, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label' %>
    <%= f.text_field :price, :class => 'form-control' %>
  </div>
  <div class="checkbox">
    <%= f.label :auto_transmission, :class => 'control-label' %>
    <%= f.check_box :auto_transmission %>
  </div>
  <div class="form-group">
    <%= f.label :mileage, :class => 'control-label' %>
    <%= f.text_field :mileage, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :remarks, :class => 'control-label' %>
    <%= f.text_field :remarks, :class => 'form-control' %>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cars_path, :class => 'btn btn-default' %>

<% end %>

app/views/cars/edit_calendar.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %><small><%= " #{@car.brand.name} #{@car.model}" %></small></h1>
</div>

<ul class="nav nav-pills">
  <li><%= link_to 'Basic', edit_car_path(@car) %></li>   
  <li><%= link_to 'Location', edit_location_car_path(@car) %></li>
  <li><%= link_to 'Pictures', edit_pictures_car_path(@car) %></li>
  <li class="active"><%= link_to 'Calendar', edit_calendar_car_path(@car) %></li>
</ul>

<%= form_for @car do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :rentaldates, :class => 'control-label' %>
    <%= f.text_field :rentaldates, :class => 'form-control', id: 'datepicker' %>
  </div>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cars_path, :class => 'btn btn-default' %>
<% end %>

<script>
  $(function() {
  $( "#datepicker" ).datepicker();
  });
</script>

app/views/cars/edit_location.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %><small><%= " #{@car.brand.name} #{@car.model}" %></small></h1>
</div>

<ul class="nav nav-pills">
  <li><%= link_to 'Basic', edit_car_path(@car) %></li>   
  <li class="active"><%= link_to 'Location', edit_location_car_path(@car) %></li>
  <li><%= link_to 'Pictures', edit_pictures_car_path(@car) %></li>
  <li><%= link_to 'Calendar', edit_calendar_car_path(@car) %></li>
</ul>

<%= form_for @car do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label' %>
    <%= f.text_field :location, :class => 'form-control' %>
  </div>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cars_path, :class => 'btn btn-default' %>

<% end %>

app/views/cars/edit_pictures.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %><small><%= " #{@car.brand.name} #{@car.model}" %></small></h1>
</div>

<ul class="nav nav-pills">
  <li><%= link_to 'Basic', edit_car_path(@car) %></li>   
  <li><%= link_to 'Location', edit_location_car_path(@car) %></li>
  <li class="active"><%= link_to 'Pictures', edit_pictures_car_path(@car) %></li>
  <li><%= link_to 'Calendar', edit_calendar_car_path(@car) %></li>
</ul>

<%= form_for @car do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="list-group">   
   <%= f.fields_for :pictures do |builder| %>
      <div class = "list-group-item-heading">
        <%= builder.label :title, class: 'control-label' %>
        <%= builder.text_field :title, class: 'form-control', placeholder: '照片描述' %>
      </div>
      <div class = "list-group-item-text">
          <td>  <%= image_tag @car.pictures[builder.index].image.url(:medium) if !@car.pictures[builder.index].title.empty? %> </td>
      </div>        
      <div class = "list-group-item-text">
        <%= builder.label :image %>
        <%= builder.file_field :image %><br>
      </div> 
   <% end %>
  </div>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cars_path, :class => 'btn btn-default' %>

<% end %>

app/views/cars/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:rentaldates) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:auto_transmission) %></th>
      <th><%= model_class.human_attribute_name(:mileage) %></th>
      <th><%= model_class.human_attribute_name(:color) %></th>
      <th><%= model_class.human_attribute_name(:remarks) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.rentaldates %></td>
        <td><%= car.price %></td>
        <td><%= car.location %></td>
        <td><%= car.auto_transmission %></td>
        <td><%= car.mileage %></td>
        <td><%= car.color %></td>
        <td><%= car.remarks %></td>
        <td><%= car.user_id %></td>
        <td><%= car.brand.name %></td>
        <td><%= car.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_car_path(car), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      car_path(car),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_car_path,
            :class => 'btn btn-primary' %>

app/views/cars/new.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<script>
  $(function() {
  $( "#datepicker" ).datepicker();
  });
</script>

<%= form_for @car, :html => { :multipart => true } do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand, :class => 'control-label' %>
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, {}, {:class=>'form-control'}) %>    
  </div>
  <div class="form-group">
    <%= f.label :model, :class => 'control-label' %>
    <%= f.text_field :model, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => 'control-label' %>
    <%= f.text_field :year, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :rentaldates, :class => 'control-label' %>
    <%= f.text_field :rentaldates, :class => 'form-control', id: 'datepicker' %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label' %>
    <%= f.text_field :price, :class => 'form-control' %>
  </div>
  <div class="checkbox">
    <%= f.label :auto_transmission, :class => 'control-label' %>
    <%= f.check_box :auto_transmission %>
  </div>
  <div class="form-group">
    <%= f.label :mileage, :class => 'control-label' %>
    <%= f.text_field :mileage, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :remarks, :class => 'control-label' %>
    <%= f.text_field :remarks, :class => 'form-control' %>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cars_path, :class => 'btn btn-default' %>

<% end %>

app/views/cars/original_index.html.erb
<h1>Listing cars</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Year</th>
      <th>Rentaldates</th>
      <th>Price</th>
      <th>Location</th>
      <th>Auto transmission</th>
      <th>Mileage</th>
      <th>Color</th>
      <th>Image url</th>
      <th>Remarks</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= image_tag car.avatar.url(:thumb) %></td>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.rentaldates %></td>
        <td><%= car.price %></td>
        <td><%= car.location %></td>
        <td><%= car.auto_transmission %></td>
        <td><%= car.mileage %></td>
        <td><%= car.color %></td>
        <td><%= car.remarks %></td>
        <td><%= link_to car.brand, car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/search.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <div style='width: 1200px;'>
      <div id="map" style='width: 1200px; height: 400px; align: center'></div>
  </div>

<%- model_class = Car -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>

        <table class="table table-striped">
          <thead>
            <tr>
              <th><%= model_class.human_attribute_name(:model) %></th>
              <th><%= model_class.human_attribute_name(:brand) %></th>
              <th><%= model_class.human_attribute_name(:price) %></th>
              <th><%= model_class.human_attribute_name(:location) %></th>
              <th><%= model_class.human_attribute_name(:year) %></th>
              <th><%= model_class.human_attribute_name(:remarks) %></th>
            </tr>
          </thead>
          <tbody>
            <% @cars.each do |car| %>
              <tr>
                <td><%= car.model %></td>
                <td><%= car.brand.name %></td>
                <td><%= car.price %></td>
                <td><%= car.location %></td>
                <td><%= car.year %></td>
                <td><%= car.remarks %></td> 
                <td><%= link_to 'Details', car, class: 'btn btn-default' %></td>               
              </tr>
            <% end %>
          </tbody>
        </table>
    
<script type="text/javascript">

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/cars/show.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:rentaldates) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:auto_transmission) %></th>
      <th><%= model_class.human_attribute_name(:mileage) %></th>
      <th><%= model_class.human_attribute_name(:color) %></th>
      <th><%= model_class.human_attribute_name(:remarks) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
        <tr>
        <td><%= @car.model %></td>
        <td><%= @car.year %></td>
        <td><%= @car.rentaldates %></td>
        <td><%= @car.price %></td>
        <td><%= @car.location %></td>
        <td><%= @car.auto_transmission %></td>
        <td><%= @car.mileage %></td>
        <td><%= @car.color %></td>
        <td><%= @car.remarks %></td>
        <td><%= @car.user_id %></td>
        <td><%= @car.brand.name %></td>
        <td><%= @car.created_at %></td>
      </tr>
  </tbody>
</table>

<% @car.pictures.each do |photo| %>
  <% if !photo.title.empty? %>
    <div class="row">
      <div class="col-md-12">
        <div class="thumbnail">
            <%= image_tag photo.image.url  %> 
          <div class="caption">
              <%= "說明 #{photo.title}" %>
          </div>
        </div>
      </div>
    </div>  
  <% else %>
  <% end %>  
<% end %>