config/routes.rb
MyCar::Application.routes.draw do
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :car_items

  resources :leases

  devise_for :users

  get "main/index"
  root 'main#index', as: 'main'
  resources :cars do
    resources :reviews
    resources :build, controller: 'cars/build'
    member do
      get 'edit_location'
      get 'edit_pictures'
      get 'edit_calendar'
    end
  end

  post 'cars/search' => 'cars#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>

<body class='<%= controller.controller_name %>'>

  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <%= link_to 'Home', main_path, class: "navbar-brand" %>          
      </div>
      <div class="collapse navbar-collapse">
        <% if user_signed_in? %>

          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'My Cars', cars_path %>
            </li>
            <li>
              <a href="#">My History</a>
            </li>            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to current_user.email, edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>

        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
          </ul>
        <% end %>

      </div><!--/.navbar-collapse -->          
    </div><!--/.container -->
  </div>
 
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= bootstrap_flash %>
        <%= yield %>
        <hr>
        <footer>
          <p>&copy; Company 2014</p>
        </footer>
      </div>
    </div>
  </div>

</body>
</html>